require('dotenv').config();
require('./database');

const Category = require('../models/category');
const Allocation = require('../models/item');

(async function() {

  await Category.deleteMany({});
  const categories = await Category.create([
     { name: 'Accessories', sortOrder: 10},
     { name: 'Accounting Fees', sortOrder: 20},
     { name: 'Accounts Payable-Trade', sortOrder: 30},
     { name: 'Accounts Receivable', sortOrder: 40},
     { name: 'Accrued Expenses', sortOrder: 50},
     { name: 'Accumulated Amortization', sortOrder: 60},
     { name: 'Accumulated Depreciation', sortOrder: 70},
     { name: 'Amortization Expense', sortOrder: 80},
     { name: 'Ask CPA', sortOrder: 90},
     { name: 'Building and Improvements', sortOrder: 100},
     { name: 'Candies', sortOrder: 110},
     { name: 'Cash-on hand', sortOrder: 120},
     { name: 'CGS-Direct Labor', sortOrder: 130},
     { name: 'CGS-Direct Materials', sortOrder: 140},
     { name: 'CGS-Indirect 1.471-11  c (2) (I)', sortOrder: 150},
     { name: 'CGS-Indirect 1.471-11  c (2) (III)', sortOrder: 160},
     { name: 'Commission Income', sortOrder: 170},
     { name: 'Consulting Expense', sortOrder: 180},
     { name: 'Contract Labor', sortOrder: 190},
     { name: 'Credit Cards Payable', sortOrder: 200},
     { name: 'Current Portion of LTD', sortOrder: 210},
     { name: 'Customer Deposits and Advances', sortOrder: 220},
     { name: 'Depreciation Expense', sortOrder: 230},
     { name: 'Due from Member', sortOrder: 240},
     { name: 'Due to Member', sortOrder: 250},
     { name: 'Dues and Subscriptions', sortOrder: 260},
     { name: 'Freight-out', sortOrder: 270},
     { name: 'Furniture and Fixtures', sortOrder: 280},
     { name: 'Gummies', sortOrder: 290},
     { name: 'Insurance Expense', sortOrder: 300},
     { name: 'Intangible Assets', sortOrder: 310},
     { name: 'Inventory', sortOrder: 320},
     { name: 'Leasehold Improvements', sortOrder: 330},
     { name: 'Legal Fees', sortOrder: 340},
     { name: 'Licensing', sortOrder: 350},
     { name: 'Machinery and Equipment', sortOrder: 360},
     { name: 'Marshmallows', sortOrder: 370},
     { name: 'Meals and Entertainment', sortOrder: 380},
     { name: 'Member Distribution', sortOrder: 390},
     { name: 'Miscellaneous Expense', sortOrder: 400},
     { name: 'Mix Edibles', sortOrder: 410},
     { name: 'Moving Expenses', sortOrder: 420},
     { name: 'Office Supplies', sortOrder: 430},
     { name: 'Other Current Assets', sortOrder: 440},
     { name: 'Other Current Liabilites', sortOrder: 450},
     { name: 'Other Income', sortOrder: 460},
     { name: 'Other Income Expense', sortOrder: 470},
     { name: 'Other Receivables', sortOrder: 480},
     { name: 'Payroll Expenses Taxes', sortOrder: 490},
     { name: 'Payroll Processing', sortOrder: 500},
     { name: 'Postage and Shipping', sortOrder: 510},
     { name: 'Prepaid Expense', sortOrder: 520},
     { name: 'Property Tax', sortOrder: 530},
     { name: 'Raw Flowers', sortOrder: 540},
     { name: 'Raw Oil', sortOrder: 550},
     { name: 'Rent', sortOrder: 560},
     { name: 'Repairs and Maintenance', sortOrder: 570},
     { name: 'Retained Earnings', sortOrder: 580},
     { name: 'Salaries and Wages', sortOrder: 590},
     { name: 'Sales Tax Payable-5.5%', sortOrder: 600},
     { name: 'Sales Tax Payable-8%', sortOrder: 610},
     { name: 'Selling & Marketing', sortOrder: 620},
     { name: 'Tinctures', sortOrder: 630},
     { name: 'Topicals', sortOrder: 640},
     { name: 'Training and Education', sortOrder: 650},
     { name: 'Travel', sortOrder: 660},
     { name: 'Utilites - Computer & Internet Exp', sortOrder: 670},
     { name: 'Utilities - Electric', sortOrder: 680},
     { name: 'Utilities - Heat', sortOrder: 690},
     { name: 'Utilities - Telephone Expense', sortOrder: 700},
     { name: 'Utilities - Water', sortOrder: 710},
     { name: 'Workers Comp', sortOrder: 720},
  ]);

  await Allocation.deleteMany({});
  const allocations = await Allocation.create([
   
     { allocation: 'Accessories', code: '40010', category: categories[0]},
     { allocation: 'Accounting Fees', code: '60170', category: categories[1]},
     { allocation: 'Accounts Payable-Trade', code: '20001', category: categories[2]},
     { allocation: 'Accounts Receivable', code: '11001', category: categories[3]},
     { allocation: 'Accrued Expenses', code: '20020', category: categories[4]},
     { allocation: 'Accumulated Amortization', code: '17010', category: categories[5]},
     { allocation: 'Accumulated Depreciation', code: '16100', category: categories[6]},
     { allocation: 'Amortization Expense', code: '60220', category: categories[7]},
     { allocation: 'Ask CPA', code: '69000', category: categories[8]},
     { allocation: 'Building and Improvements', code: '16020', category: categories[9]},
     { allocation: 'Candies', code: '40040', category: categories[10]},
     { allocation: 'Cash-on hand', code: '10001', category: categories[11]},
     { allocation: 'CGS-Direct Labor', code: '50200', category: categories[12]},
     { allocation: 'Salary and Wages-Position', code: '50210', category: categories[12]},
     { allocation: 'Payroll taxes-Position', code: '50220', category: categories[12]},
     { allocation: 'Fringe-Position', code: '50230', category: categories[12]},
     { allocation: 'Workers Comp-Position', code: '50240', category: categories[12]},
     { allocation: 'Salary and Wages-Position', code: '50250', category: categories[12]},
     { allocation: 'Payroll taxes-Position', code: '50260', category: categories[12]},
     { allocation: 'Fringe-Position', code: '50270', category: categories[12]},
     { allocation: 'Workers Comp-Position', code: '50280', category: categories[12]},
     { allocation: 'Contract Labor', code: '50290', category: categories[12]},
     { allocation: 'CGS-Direct Materials', code: '50001', category: categories[13]},
     { allocation: 'Growing Materials-Phase 1', code: '50010', category: categories[13]},
     { allocation: 'Growing Materials-Phase 2', code: '50012', category: categories[13]},
     { allocation: 'Extraction Materials', code: '50020', category: categories[13]},
     { allocation: 'Extraction Processing', code: '50022', category: categories[13]},
     { allocation: 'Dispersion', code: '50030', category: categories[13]},
     { allocation: 'Cooking Materials', code: '50040', category: categories[13]},
     { allocation: 'Packaging and Labels', code: '50090', category: categories[13]},
     { allocation: 'Purchases for resale', code: '50100', category: categories[13]},
     { allocation: 'CGS-Indirect 1.471-11  c (2) (I)', code: '50500', category: categories[14]},
     { allocation: 'Salaries and Wages - Indirect', code: '50510', category: categories[14]},
     { allocation: 'Payroll taxes-Indirect', code: '50520', category: categories[14]},
     { allocation: 'Fringe-Indirect', code: '50530', category: categories[14]},
     { allocation: 'Workers Comp-Indirect', code: '50540', category: categories[14]},
     { allocation: 'Tools and Equip not Capitalized', code: '50550', category: categories[14]},
     { allocation: 'Equipment repair', code: '50552', category: categories[14]},
     { allocation: 'QC and Lab', code: '50560', category: categories[14]},
     { allocation: 'Licensing', code: '50565', category: categories[14]},
     { allocation: 'Materials and Supplies', code: '50570', category: categories[14]},
     { allocation: 'Security System', code: '50580', category: categories[14]},
     { allocation: 'Repairs and Maintenance', code: '50590', category: categories[14]},
     { allocation: 'Electric', code: '50610', category: categories[14]},
     { allocation: 'Water', code: '50620', category: categories[14]},
     { allocation: 'Heat', code: '50630', category: categories[14]},
     { allocation: 'Grow lighting', code: '50640', category: categories[14]},
     { allocation: 'Rent', code: '50650', category: categories[14]},
     { allocation: 'CGS-Indirect 1.471-11  c (2) (III)', code: '51000', category: categories[15]},
     { allocation: 'Personal Property Taxes', code: '51010', category: categories[15]},
     { allocation: 'Depreciation of Manufacturing Equip', code: '51020', category: categories[15]},
     { allocation: 'Admin Costs for Production Activity', code: '51030', category: categories[15]},
     { allocation: 'Member Salaries for Production Activity', code: '51040', category: categories[15]},
     { allocation: 'Insurance for Production Activity', code: '51050', category: categories[15]},
     { allocation: 'Commission Income', code: '40200', category: categories[16]},
     { allocation: 'Consulting Expense', code: '60160', category: categories[17]},
     { allocation: 'Contract Labor', code: '60050', category: categories[18]},
     { allocation: 'Credit Cards Payable', code: '20010', category: categories[19]},
     { allocation: 'Current Portion of LTD', code: '20100', category: categories[20]},
     { allocation: 'Customer Deposits and Advances', code: '20040', category: categories[21]},
     { allocation: 'Depreciation Expense', code: '60210', category: categories[22]},
     { allocation: 'Due from Member', code: '12001', category: categories[23]},
     { allocation: 'Due to Member', code: '20042', category: categories[24]},
     { allocation: 'Dues and Subscriptions', code: '60130', category: categories[25]},
     { allocation: 'Freight-out', code: '40195', category: categories[26]},
     { allocation: 'Furniture and Fixtures', code: '16010', category: categories[27]},
     { allocation: 'Gummies', code: '40090', category: categories[28]},
     { allocation: 'Insurance Expense', code: '60080', category: categories[29]},
     { allocation: 'Intangible Assets', code: '17000', category: categories[30]},
     { allocation: 'Inventory', code: '13001', category: categories[31]},
     { allocation: 'Plants in Process', code: '13010', category: categories[31]},
     { allocation: 'Supplies-Plant Growth', code: '13020', category: categories[31]},
     { allocation: 'Supplies-Product Production', code: '13030', category: categories[31]},
     { allocation: 'FG-Raw Oil', code: '13040', category: categories[31]},
     { allocation: 'FG-Gummies', code: '13050', category: categories[31]},
     { allocation: 'FG-Sleepies', code: '13060', category: categories[31]},
     { allocation: 'FG-Tinctures', code: '13070', category: categories[31]},
     { allocation: 'FG-Topicals', code: '13080', category: categories[31]},
     { allocation: 'FG-Bath Bombs', code: '13090', category: categories[31]},
     { allocation: 'FG-Accessories Other', code: '13100', category: categories[31]},
     { allocation: 'Leasehold Improvements', code: '16030', category: categories[32]},
     { allocation: 'Legal Fees', code: '60180', category: categories[33]},
     { allocation: 'Licensing', code: '60185', category: categories[34]},
     { allocation: 'Machinery and Equipment', code: '16000', category: categories[35]},
     { allocation: 'Marshmallows', code: '40060', category: categories[36]},
     { allocation: 'Meals and Entertainment', code: '60120', category: categories[37]},
     { allocation: 'Member Distribution', code: '30050', category: categories[38]},
     { allocation: 'Miscellaneous Expense', code: '60420', category: categories[39]},
     { allocation: 'Mix Edibles', code: '40095', category: categories[40]},
     { allocation: 'Moving Expenses', code: '60410', category: categories[41]},
     { allocation: 'Office Supplies', code: '60140', category: categories[42]},
     { allocation: 'Other Current Assets', code: '14050', category: categories[43]},
     { allocation: 'Other Current Liabilites', code: '20030', category: categories[44]},
     { allocation: 'Other Income', code: '40900', category: categories[45]},
     { allocation: 'Other Income Expense', code: '70000', category: categories[46]},
     { allocation: 'Other Income', code: '70010', category: categories[46]},
     { allocation: 'Interest Expense', code: '70020', category: categories[46]},
     { allocation: 'Bank Charges', code: '70030', category: categories[46]},
     { allocation: 'Other Expense', code: '70110', category: categories[46]},
     { allocation: 'Other Receivables', code: '11005', category: categories[47]},
     { allocation: 'Payroll Expenses Taxes', code: '60020', category: categories[48]},
     { allocation: 'Payroll Processing', code: '60040', category: categories[49]},
     { allocation: 'Postage and Shipping', code: '60150', category: categories[50]},
     { allocation: 'Prepaid Expense', code: '14001', category: categories[51]},
     { allocation: 'Property Tax', code: '60195', category: categories[52]},
     { allocation: 'Raw Flowers', code: '40070', category: categories[53]},
     { allocation: 'Raw Oil', code: '40030', category: categories[54]},
     { allocation: 'Rent', code: '60190', category: categories[55]},
     { allocation: 'Repairs and Maintenance', code: '60310', category: categories[56]},
     { allocation: 'Retained Earnings', code: '30010', category: categories[57]},
     { allocation: 'Salaries and Wages', code: '60010', category: categories[58]},
     { allocation: 'Sales Tax Payable-5.5%', code: '20012', category: categories[59]},
     { allocation: 'Sales Tax Payable-8%', code: '20013', category: categories[60]},
     { allocation: 'Selling & Marketing', code: '60070', category: categories[61]},
     { allocation: 'Tinctures', code: '40080', category: categories[62]},
     { allocation: 'Topicals', code: '40050', category: categories[63]},
     { allocation: 'Training and Education', code: '60060', category: categories[64]},
     { allocation: 'Travel', code: '60110', category: categories[65]},
     { allocation: 'Utilites - Computer & Internet Exp', code: '60350', category: categories[66]},
     { allocation: 'Utilities - Electric', code: '60320', category: categories[67]},
     { allocation: 'Utilities - Heat', code: '60330', category: categories[68]},
     { allocation: 'Utilities - Telephone Expense', code: '60360', category: categories[69]},
     { allocation: 'Utilities - Water', code: '60340', category: categories[70]},
     { allocation: 'Workers Comp', code: '60030', category: categories[71]}
 ]);

  console.log(allocations)

  process.exit();

})();